### ISSUE TITLE
People In The News Tab Doesn't Show It Has Errors

### ISSUE THREAD

**Issue by ascii-dev** [CodeForAfrica/gmmp#77]
Oh... Forgot one issue @ascii-dev.

After validating that the optional questions are required, the **tab** itself doesn't show that that specific panel needs attention i.e. doesn't get the red underline:
![Peek 2020-09-08 09-03](https://user-images.githubusercontent.com/1779590/92439434-802b9000-f1b3-11ea-8732-d3ed04d303d4.gif)

This means people won't know to check for errors there.

_Originally posted by @kilemensi in https://github.com/CodeForAfrica/gmmp/pull/76#issuecomment-688641360_

**Comment by kilemensi** [comment]
We have [PivotalTracker](https://www.pivotaltracker.com/n/projects/2420193) for this @ascii-dev
